# version: '3.8'
# services:
#   localstack:
#     image: localstack/localstack
#     container_name: localstack
#     ports:
#       - "4566:4566"
#       - "4576:4576"
#     environment:
#       - SERVICES=sqs,s3
#       - DEBUG=1
#       - AWS_ACCESS_KEY_ID=test
#       - AWS_SECRET_ACCESS_KEY=test
#     volumes:
#       - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

version: "3.8"
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs
      - DEBUG=1
